name: Re-use notify.yml workflow
on:
  pull_request:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
  notify:
    needs: [do-something]
    if: failure()
    uses: penchef/slack-committer/.github/workflows/notify.yml@main
    secrets: inherit
    with:
      failure: ${{ needs.do-something.results == 'failure' }}

