name: Re-use notify.yml workflow
on:
  pull_request:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
  # the call to the reuseable workflow has to occur at the "jobs" level
  # the call cannot be made from a "step",
  # see https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  notify:
    needs: [ do-something ]
    if: ${{ always() && ( contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') ) }}
    uses: penchef/slack-committer/.github/workflows/notify.yml@main
    secrets: inherit
    with:
      failure: true
  debug:
    runs-on: ubuntu-latest
    needs: [ do-something ]
    if: ${{ always() }}
    steps:
      - name: foo
        env:
          FOO: ${{ contains(needs.*.result, 'failure')  }}
          BAR: ${{ contains(needs.*.result, 'skipped') }}
        run: |
          echo "FOO $FOO"
          echo "BAR $BAR"
