name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - name: release
        if: ${{ endsWith(github.ref, '/main') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: update v1 tag
        if: ${{ endsWith(github.ref, '/main') }}
        run: 'git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
