name: Test
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - name: read users.json
        id: read-users
        run: echo "users=$(jq . users.json) >> $GITHUB_OUTPUT"
      - name: Resolve slack committer with users.json
        id: slack-committer
        uses: livelyhood/slack-committer@main
        with:
          user-mapping: ${{ steps.read-users.outputs.users }}
      - run: echo ${{ steps.slack-committer.outputs.username }}
      - name: Resolve slack committer
        id: slack-committer-string
        uses: livelyhood/slack-committer@main
        with:
          user-mapping: >
            {
              "Penchef": "UUSAQBVDZ",
              "fallback": "XYZXYZXYZ"
            }
      - run: echo ${{ steps.slack-committer-string.outputs.username }}
