name: Test
on:
  pull_request:
  workflow_dispatch:
    inputs:
      status:
        description: 0 or 1
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - name: read users.json
        id: read-users
        run:  echo users=$(jq . users.json) >> $GITHUB_OUTPUT
      - name: Resolve slack committer
        id: slack-committer
        uses: penchef/slack-committer@v1.2
        with:
          user-mapping: ${{ steps.read-users.outputs.users }}
      - run: echo ${{ steps.slack-committer.outputs.username }}
      - run: exit ${{  inputs.status  }}
      - name: Notify committer
        uses: penchef/slack-committer/.github/workflows/notify.yml@main
        with:
          failure: failure()
          secrets: inherit

